export const ALL_MISSIONS = [
  {
    id: 1,
    startDate: '2024-09-01',
    endDate: '2024-09-02',
    imgUrl: 'https://placehold.co/600?text=Mission1',
    title: '미션 1 제목',
    content: '미션1 설명',
    week: {
      mon: true,
      tue: false,
      wed: true,
      thu: false,
      fri: true,
      sat: false,
      sun: true,
    },
    userName: 'John Doe',
    participants: [
      {
        id: 1,
        userName: 'John Doe',
        imgUrl: 'https://example.com/user1.jpg',
        banned: false,
      },
    ],
  },
  {
    id: 2,
    startDate: '2024-09-01',
    endDate: '2024-09-02',
    imgUrl: 'https://placehold.co/600?text=Mission2',
    title: '미션 2 제목',
    content: '미션2 설명',
    week: {
      mon: true,
      tue: false,
      wed: true,
      thu: false,
      fri: true,
      sat: false,
      sun: true,
    },
    userName: 'John Doe',
    participants: [
      {
        id: 1,
        userName: 'John Doe',
        imgUrl: 'https://example.com/user1.jpg',
        banned: false,
      },
    ],
  },
  {
    id: 3,
    startDate: '2024-09-01',
    endDate: '2024-09-02',
    imgUrl: 'https://placehold.co/600?text=Mission3',
    title: '미션 3 제목',
    content: '미션3 설명',
    week: {
      mon: true,
      tue: false,
      wed: true,
      thu: false,
      fri: true,
      sat: false,
      sun: true,
    },
    userName: 'John Doe',
    participants: [
      {
        id: 1,
        userName: 'John Doe',
        imgUrl: 'https://example.com/user1.jpg',
        banned: false,
      },
    ],
  },
  {
    id: 4,
    startDate: '2024-09-01',
    endDate: '2024-09-02',
    imgUrl: 'https://placehold.co/600?text=Mission4',
    title: '미션 4 제목',
    content: '미션4 설명',
    week: {
      mon: true,
      tue: false,
      wed: true,
      thu: false,
      fri: true,
      sat: false,
      sun: true,
    },
    userName: 'John Doe',
    participants: [
      {
        id: 1,
        userName: 'John Doe',
        imgUrl: 'https://example.com/user1.jpg',
        banned: false,
      },
    ],
  },
];
